services:
  backend:
    build: ./backend
    container_name: todo-backend
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
      - ./backend/.env.dev
    healthcheck:
      test: "curl --fail http://backend:8000/api || exit 1"      
      interval: 1s
      timeout: 2s
      retries: 100
    depends_on:
      db:
        condition: service_healthy
        
  frontend:
    build: ./frontend
    container_name: todo-frontend
    volumes:
      - ./frontend/src:/app/src
    depends_on:
      backend:
        condition: service_healthy
    env_file:
      - ./frontend/.env
    healthcheck:
      test: "curl --fail --request GET --url 'http://localhost:5173' || exit 1"
      interval: 1s
      timeout: 2s
      retries: 100

  db:
    image: postgres:17
    container_name: todo-db
    healthcheck:
      test: ["CMD", "pg_isready", "-d", "todo", "-U", "postgres"]
      interval: 1s
      timeout: 2s
      retries: 100
    environment:  
      POSTGRES_DB: todo
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/postgres-data/data:/var/lib/postgresql/data
      - ./db/dumps:/dumps
    ports:
      - "5432:5432"

  adminer:
    image: adminer
    container_name: todo-adminer
    depends_on:
      db:
        condition: service_healthy
    ports:
      - 8080:8080

  apigateway:
    image: nginx
    container_name: todo-nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      backend:
        condition: service_healthy
      frontend:
        condition: service_healthy
    ports:
      - "7002:80"

  redis:
    image: redis
    container_name: todo-redis